### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by DonatassVZ** [yandex-money/yandex-checkout-payments-swift#1]
Установил  SDK через CocoaPods  как указано https://kassa.yandex.ru/docs/client-sdks/#sdk-dlq-ios
TrustDefender.framework - не указано , где брать етот фреймворк - поискав немного взял его из Github  ,  подключаеться он не так как в инструкции так как ошибку вибивает как раз на модуль yandex-checkout-payments-swift  - на него и нада делать подключение TrustDefender'а .  После етого  видно что фреймоврк импортируеться но  проблеми з файлом ThreatMetrixService.swift   - там используються необявление типи - например THMProfileHandle и проект не может собраться в среде Xcode.

**Comment by MetalheadSanya** [comment]
Библиотеки TrustDefender.framework в открытом доступе нет, поэтому у вас и возникли такие проблемы. Обратитесь к нашим коллегам по подключению мобильной кассы и они вам помогут.

**Comment by AlexanderNaumov** [comment]
> Открытый исходный код
> 
> Несколько месяцев после запуска мы распространяли библиотеку очень неудобно — делились ссылкой на сайт или отправляли файлы по почте. Хорошие ребята так не делают — они выкладывают всё на GitHub под лицензией MIT. Вот мы ровно так и сделали.

Смысл от вашего открытого исходного кода, если его собрать никто не может?

**Comment by MetalheadSanya** [comment]
Мерчанты работающие с нами могут спокойно собрать проект и делают это.

**Comment by AlexanderNaumov** [comment]
Приходиться лепить такие костыли:
```
#!/bin/bash
git clone https://bitbucket.org/haymob/trustdefender.git
mkdir -pv Carthage/Build/iOS
mv trustdefender/TrustDefender.framework Carthage/Build/iOS
rm -rf trustdefender
carthage update --platform iOS
```
А от документации где вы предлагаете вручную скопировать TrustDefender.framework в папку Frameworks хотелось плакать :)

**Comment by MetalheadSanya** [comment]
Поверьте, если бы у нас была возможность сделать интеграцию проще и удобнее, то мы бы обязательно бы это сделали
