### ISSUE TITLE
Payment button is not visible on iOS 10

### ISSUE THREAD

**Issue by Hardenn** [yandex-money/yandex-checkout-payments-swift#11]
Hey!

This screen doesn't show payment button on iOS 10 (iOS 11 is all good). So next step is blocked.

Note: don't forget to check button presence after fix when turning back from 3ds web view.

![2018-08-16 18 41 48](https://user-images.githubusercontent.com/1327323/44219242-3ca4fa00-a184-11e8-83bb-217cca7949f1.jpg)

**Comment by oltv00** [comment]
Fixed in 1.3.4 - current version
