### ISSUE TITLE
Web View has horizontal scroll indicator in wrong place

### ISSUE THREAD

**Issue by Hardenn** [yandex-money/yandex-checkout-payments-swift#13]
Hey!

This video below shows incorrect horizontal scroll indicator in 3ds web view. It looks so on every iOS version.

Library: 1.3.3

[ios-3ds-bugs.mp4.zip](https://github.com/yandex-money/yandex-checkout-payments-swift/files/2306082/ios-3ds-bugs.mp4.zip)

**Comment by oltv00** [comment]
Fixed in https://github.com/yandex-money/yandex-checkout-payments-swift/releases/tag/2.0.0
