### ISSUE TITLE
Не работает авторизация

### ISSUE THREAD

**Issue by artem-tverdokhlebov** [yandex-money/yandex-checkout-payments-swift#15]
Сделали все по инструкции, после oauth перекидывает в приложение и не авторизуется, как быть?

**Comment by oltv00** [comment]
Актуальная ли проблема на текущий момент?

Проблема с авторизаций может возникать:
1. Ошибка при интеграции mSDK. (ниже будет актуальная инструкция)
2. Возможно ошибка в настройках магазина.

Вот инструкция по подключению.
Если все сделано по инструкции, будем смотреть что может быть не так.

1. Зарегистрируйте свое приложение в [Яндекс.OAuth](https://oauth.yandex.ru/) и сохраните __ID__.
   - Введите название приложения.
   - В разделе __API Яндекс.Паспорта__ необходимо выбрать __Доступ к логину, имени и фамилии, полу__

2. Добавьте в Info.plist следующие строки:

  ```plistbase
  <key>LSApplicationQueriesSchemes</key>
  <array>
      <string>yandexauth</string>
      <string>yandexauth2</string>
  </array>
  <key>CFBundleURLTypes</key>
  <array>
      <dict>
          <key>CFBundleURLName</key>
          <string>YandexLoginSDK</string>
          <key>CFBundleURLSchemes</key>
          <array>
              <string>yx<ID из Яндекс.OAuth></string>
          </array>
      </dict>
  </array>
  ```

3. Настройте Entitlements

В своем проекте в разделе `Capabilities` включите `Associated Domains` и добавьте домен по шаблону:
>applinks:yx<ID из Яндекс.OAuth>.oauth.yandex.ru.

Например, если ваш ID из Яндекс.OAuth — `333`, домен будет таким:
>applinks:yx333.oauth.yandex.ru.

4. Добавьте код из примера в AppDelegate.

```swift
func application(_ application: UIApplication,
                 didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    do {
        try YandexLoginService.activate(withAppId: /* ID из Яндекс.OAuth */)
    } catch {
        // process error
    }
    return true
}

func application(_ application: UIApplication,
                 continue userActivity: NSUserActivity,
                 restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
    YandexLoginService.processUserActivity(userActivity)
    return true
}

func application(_ app: UIApplication,
                 open url: URL,
                 options: [UIApplication.OpenURLOptionsKey: Any]) -> Bool {
    return YandexLoginService.handleOpen(url, sourceApplication: options[.sourceApplication] as? String)
}
```
