### ISSUE TITLE
extension UIButton ломает кнопки в проекте

### ISSUE THREAD

**Issue by mstroshin** [yandex-money/yandex-checkout-payments-swift#24]
Доброго времени суток.
Два метода из UIButton+Style.swift [[раз](https://github.com/yandex-money/yandex-checkout-payments-swift/blob/32da4afac2a710ddd385a08613c56c2334f0f2b2/YandexCheckoutPayments/Atomic%20Design/Molecules/UIKit%2BStyles/UIButton%2BStyle.swift#L184), [два](https://github.com/yandex-money/yandex-checkout-payments-swift/blob/32da4afac2a710ddd385a08613c56c2334f0f2b2/YandexCheckoutPayments/Atomic%20Design/Molecules/UIKit%2BStyles/UIButton%2BStyle.swift#L189)] ломают размеры некоторых кнопок по всему проекту.

**Comment by oltv00** [comment]
@mstroshin 
Добрый день.
Спасибо за репорт.
Сегодня выпустим версию, которая исправит это.

**Comment by oltv00** [comment]
@mstroshin 
https://github.com/yandex-money/yandex-checkout-payments-swift/releases/tag/1.3.5
Выпустили версию с фиксом.
