### ISSUE TITLE
Problem with install pods

### ISSUE THREAD

**Issue by alecsechechel** [yandex-money/yandex-checkout-payments-swift#25]
Please check code below, problem downloading YandexMobileMetrica.

Also could I delete these pods?
YandexLoginSDK (2.0.2)
Installing YandexMobileMetrica (3.1.2)

I want use only payment in my app.

`Installing YandexMobileMetrica (3.1.2)

[!] Error installing YandexMobileMetrica
[!] /usr/bin/curl -f -L -o /var/folders/7v/f8d9tpr572q2b0szq1b5dn400000gn/T/d20181125-79702-15s6rzi/file.zip https://storage.mds.yandex.net/get-appmetrica-mobile-sdk/128534/YandexMobileMetrica-3.1.2-ios-0ed40305-b027-4c82-9401-865906c14d3f.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to storage.mds.yandex.net port 443: Operation timed out

Thanks
`

**Comment by oltv00** [comment]
@alecsechechel 

>Please check code below, problem downloading YandexMobileMetrica.

Is problem still actual?
I think it was a temporal problem.

>Also could I delete these pods?

No, you can't.
These pods is important part of library.

**Comment by oltv00** [comment]
@simorakkaus 

Привет!

>для чего YandexMobileMetrica использует IDFA и какие из этих вариантов подходит?

Вот официальная информация по этому вопросу:
https://tech.yandex.ru/appmetrica/doc/troubleshooting/moderation-docpage/
![image](https://user-images.githubusercontent.com/14943414/52368232-feb3cf00-2a5e-11e9-81aa-c12f0019d2d1.png)

**Comment by simorakkaus** [comment]
@oltv00 да, спасибо :)
