### ISSUE TITLE
YandexCheckoutPaymentsApi 1.1.0 issue

### ISSUE THREAD

**Issue by Banck** [yandex-money/yandex-checkout-payments-swift#27]
После обновления подов, а именно после того как обновился YandexCheckoutPaymentsApi 1.1.0
появились ошибки:
![image](https://user-images.githubusercontent.com/6259254/51659834-5cb3d180-1fde-11e9-8c15-c9b055684027.png)
Версия YandexCheckoutPayments - 1.3.7

**Comment by oltv00** [comment]
Привет!

Спасибо за репорт. В следующей версии обязательно исправим.

На текущий момент можно указать зависимость явно на старую версию.

Пропишите в Podfile:

```
pod 'YandexCheckoutPaymentsApi',
        :git => 'https://github.com/yandex-money/yandex-checkout-payments-api-swift.git',
        :tag => '1.0.3'
```

И выполните `pod update YandexCheckoutPaymentsApi`

**Comment by oltv00** [comment]
Fixed in https://github.com/yandex-money/yandex-checkout-payments-swift/releases/tag/2.0.0
