### ISSUE TITLE
Вручную импортировать проект без CocoaPods

### ISSUE THREAD

**Issue by bulatshafigullin** [yandex-money/yandex-checkout-payments-swift#29]
Добрый день, у меня проект на react-native, и cocoapods уже заточен под него, use_frameworks использовать затруднительно. Есть ли возможность вручную вкатить проект Yandex Checkout Payments SDK в workspace?  Все зависимости я уже собрал с помощью carthage (FunctionalSwift, When и т.д) TrustDefender тоже выдали.

**Comment by oltv00** [comment]
@bulatshafigullin 

Добрый день.

>Есть ли возможность вручную вкатить проект Yandex Checkout Payments SDK в workspace?
>Все зависимости я уже собрал с помощью carthage

На данный момент мы официально не поддерживаем Carthage, т.к. есть некоторые проблемы с нашими зависимостями, в следующей версии мы планируем добавить полноценную поддержку.

>у меня проект на react-native, и cocoapods уже заточен под него, use_frameworks использовать затруднительно

Вы пробовали  [этот solution](https://github.com/react-native-community/react-native-maps/issues/2324)?

**Comment by bulatshafigullin** [comment]
Спасибо огромное! Решение рабочее, однако пришлось все статические зависимости вынести из Podfile и вручную привязать к workspace. Но решение рабочее

**Comment by whalemare** [comment]
Если вы ищете решение для react-native, то можете посмотреть в сторону этой библиотеки, которую мы написали:
https://github.com/lamantin-group/react-native-yandex-payment

**Comment by oltv00** [comment]
@bulatshafigullin 
Привет!
Актуальна ли еще проблема?

**Comment by alphatroya** [comment]
Думаю что проблема еще очень даже актуальна. Многие команды не используют Cocoapods, некоторые не используют вообще никаких PM. На этот случай всегда должна быть доступна собранная сборка для ручной интеграции.
