### ISSUE TITLE
Проблема с библиотекой 

### ISSUE THREAD

**Issue by alekseyykt** [yandex-money/yandex-checkout-payments-swift#3]
Получили доступ на использование библиотеки у ваших менеджеров, поставили, и после того как мы создали платежный токен и отправили его на сервер, в ответ получаем ссылку для переадресации на 3DSecure и в этот момент приложение падает с ошибкой в файле ResourceLoader.swift (Подробнее на скриншоте)
![2018-07-24 16 33 02](https://user-images.githubusercontent.com/4454971/43141743-5d0f0664-8f5f-11e8-97e7-b8f286c178c9.png)

Устанавливали все по инструкции. Версия 1.3.1.
После получения токена в tokenizationModule окно не закрывалось.

**Comment by alekseyykt** [comment]
Закрытие окна оплаты после редиректа 3DSecure как не работало, так и сейчас не работает. Притом, когда открывается веб-вьюха для ввода кода, Вы не убираете largeTitle у navigationBar'a из-за чего все выглядит как-то так
![img_0282](https://user-images.githubusercontent.com/4454971/43311947-8b3e45e0-9194-11e8-8e7a-2adbeadafd70.PNG)

**Comment by MetalheadSanya** [comment]
We partially fix problem. No lib does not crash on open 3ds screen

**Comment by alekseyykt** [comment]
Теперь дважды вызывается func didSuccessfullyPassedCardSec(on module: TokenizationModuleInput)

**Comment by oltv00** [comment]
>Приложение падает с ошибкой в файле ResourceLoader.swift
>Закрытие окна оплаты после редиректа 3DSecure как не работало, так и сейчас не работает.

В версии [2.0.2](
https://github.com/yandex-money/yandex-checkout-payments-swift/releases/tag/2.0.2) проблемы не воспроизводятся.
