### ISSUE TITLE
Хочется странного... Qiwi не работает

### ISSUE THREAD

**Issue by chepil** [yandex-money/yandex-checkout-payments-swift#30]
В api для mSDK сказано - 

/// All the available methods.
    public static let all: PaymentMethodTypes = [.bankCard, .yandexMoney, .applePay, .sberbank]

Также, определен enum:

public enum PaymentMethodType: String, Codable {
    /// Bank Card.
    case bankCard = "bank_card"
    /// Cash.
    case cash
    /// Qiwi.
    case qiwi
    /// Alfabank.
    case alfabank
    /// Webmoney.
    case webmoney
    /// Yandex Money.
    case yandexMoney = "yandex_money"
    /// Sberbank.
    case sberbank
    /// ApplePay.
    case applePay = "apple_pay"
}

Как проводить платежи через qiwi кошелек, при условии, что нет доступного qiwi в PaymentMethodTypes ? 

Qiwi не поддерживается ???

P.S. Красивые Казашки не могут платить через банковские карты. Там вообще, через карты фиг заплатишь, так как банки по умолчанию блокируют все интернет платежи. Зато qiwi там живет и царствует. Все платят кивёй. Поэтому хочется удовлетворить казашек... И это серьезно. Сам в шоке...

**Comment by oltv00** [comment]
@chepil 

>Как проводить платежи через qiwi кошелек, при условии, что нет доступного qiwi в PaymentMethodTypes ?

Сейчас - никак(

>Qiwi не поддерживается ???

На текущий момент в SDK Qiwi не поддерживается.

>P.S. Красивые Казашки не могут платить через банковские карты. Там вообще, через карты фиг заплатишь, так как банки по умолчанию блокируют все интернет платежи. Зато qiwi там живет и царствует. Все платят кивёй. Поэтому хочется удовлетворить казашек... И это серьезно. Сам в шоке...

Я передам эту информацию нашему менеджеру, и постараюсь сориентировать возможность добавления этого функционала и срокам.

**Comment by chepil** [comment]
Олег, спасибо! Мы, со своей стороны, тоже будем мучать ваших менеджеров.

**Comment by oltv00** [comment]
@chepil 

Я получил ответ от менеджера:

```
```

**Comment by chepil** [comment]
Олег, спасибо, так и предполагал, но у меня свои менеджеры :-) Поэтому задал вопрос. Еще раз спасибо за помощь!
