### ISSUE TITLE
Русская локализация

### ISSUE THREAD

**Issue by yargeel** [yandex-money/yandex-checkout-payments-swift#32]
Добрый день!

Подскажите, как "включить" русский язык в интерфейсе (в примере - "банковская карта", "к оплате" и т.д., в собственном проекте - "bank card", to be paid"...)?

Есть ли подробная документация или описание?

**Comment by oltv00** [comment]
@yargeel 

Добрый день!
Локализация интерфейса зависит от локализации устройства.

Попробуйте поменять язык на телефоне на Русский.

**Comment by yargeel** [comment]
И в эмуляторе и на рабочем устройстве установлен русский язык.
Однако пример СДК и рабочий проект ведут себя, как описано в вопросе.

**Comment by MetalheadSanya** [comment]
@yargeel Does your app support russian language? You must use russian lang in project settings.

If you do not change default setting, you use base localization (english)

**Comment by yargeel** [comment]
> @yargeel Does your app support russian language? You must use russian lang in project settings.
> 
> If you do not change default setting, you use base localization (english)

Oh, thank you very much. The reason was really in localization by default - thank you again!
