### ISSUE TITLE
Есть ли возможность стилизации ViewController'а возвращаемого TokenizationAssembly?

### ISSUE THREAD

**Issue by ivanovean** [yandex-money/yandex-checkout-payments-swift#33]
Добрый день! Спасибо за библиотеку, всё работает отлично.
Возник следующий вопрос: существует ли какая-нибудь возможность стилизации ViewController'а возвращаемого TokenizationAssembly.makeModule? 
Мы используем только оплату через Apple Pay и желтый цвет индикатора не очень вписывается в дизайн приложения.
Поэтому очень хотелось бы немного изменить цвет индикатора либо скрыть этот ViewController.
Заранее спасибо за ответ.

**Comment by MetalheadSanya** [comment]
You can change tint color of view controller or window. This will change color of activity indicator

**Comment by ivanovean** [comment]
> You can change tint color of view controller or window. This will change color of activity indicator

Насколько я вижу по коду, ActivityIndicatorView проставляется Styles.heavyLight, в таком случае activity проставляется Styles.secondary с spinnerColor = .mustard.
Так что проставление tintColor на ситуацию не влияет.
```
self.paymentVC = TokenizationAssembly.makeModule(inputData: inputData, moduleOutput: inVC)
if let gPaymentVC = self.paymentVC {
   gPaymentVC.view.tintColor = UIColor(red: 110.0/255, green: 195.0/255, blue: 49.0/255, alpha:1)
   inVC.present(gPaymentVC, animated: true, completion: nil)
}
```

**Comment by MetalheadSanya** [comment]
We will fix this style for using tint color.

**Comment by ivanovean** [comment]
> We will fix this style for using tint color.
> […](#)

Many thanks

**Comment by oltv00** [comment]
@ivanovean 
В версиях >=2.0.5 можно конфигурировать модель `CustomizationSettings`, передавая ее в `TokenizationModuleInputData` в параметре `customizationSettings`

Это будет менять цвет всех основных элементов
