### ISSUE TITLE
Не загружается страница банка для ввода 3ds кода из смс

### ISSUE THREAD

**Issue by yargeel** [yandex-money/yandex-checkout-payments-swift#35]
Добрый день!

Периодически не загружается страница банка для ввода кода из смс:
https://geel.pro/yandex.png
Если через некоторое время вернуться на предыдущую страницу по нажатию кнопки "банковская карта" и повторить платеж (не меняя данных) - с большой вероятностью повторный платеж пройдет успешно. Но иногда пауза затягивается до пары часов.

**Comment by oltv00** [comment]
Учитывая что 3DS выполняется в WebView, не думаю что тут можно что то сделать.
