### ISSUE TITLE
Не закрывается окно оплаты

### ISSUE THREAD

**Issue by whalemare** [yandex-money/yandex-checkout-payments-swift#38]
![Снимок экрана 2019-09-05 в 10 25 00](https://user-images.githubusercontent.com/9128731/64333004-db0a3480-cfff-11e9-81fb-6c5864c4f18f.png)

Показываю viewController вот так

```swift
DispatchQueue.main.async {
    self.viewController = TokenizationAssembly.makeModule(
        inputData: inputData,
        moduleOutput: self
    )
    let rootViewController = UIApplication.shared.keyWindow!.rootViewController!
    rootViewController.present(self.viewController!, animated: true, completion: nil)
}
```

Он отображается как всплывающее окно, но не закрывается, когда нажимаешь в пустое место над экраном.
что нужно поменять, чтобы он закрывался?

**Comment by oltv00** [comment]
@whalemare
Привет!
При клике вне области контейнера должен вызываться метод `func didFinish(on module:, with error:)` (или `func didFinish(on module:)` если версия меньше 2.2.0) протокола `TokenizationModuleOutput`.

Покажи код его обработки, и заодно проверь вызывается ли он.

**Comment by whalemare** [comment]
@oltv00 спасибо за объяснение, разобрался!
Использовал код для библиотеки ниже 2.2.0, после обновился на 2.2.0, но не добавил обработку метода `func didFinish(on module:, with error:)`
