### ISSUE TITLE
В iOS 13 падает TrustDefender

### ISSUE THREAD

**Issue by yargeel** [yandex-money/yandex-checkout-payments-swift#40]
Добрый день!
В iOS 13 падает модуль TrustDefender, в 12 и более ранних все ок.
Скрин: https://prnt.sc/pkbtyl
Секция podfile:
 pod 'FunctionalSwift'
    pod 'CardIO', :git => 'https://github.com/card-io/card.io-iOS-SDK.git', :tag => '5.4.1'    
    pod 'SwiftLint'
    pod 'YandexCheckoutPayments',
        :git => 'https://github.com/yandex-money/yandex-checkout-payments-swift.git', :tag => '2.2.2' 
    pod 'YandexMobileMetricaPush/Dynamic', '0.8.0'
    pod 'YandexMobileMetrica/Dynamic', '~> 3.7.0'

**Comment by oltv00** [comment]
@yargeel 
Добрый день.
Запросите у вашего менеджера по подключению Яндекс Кассы новую версию ThreatMetrix iOS SDK 5.4-84, и попробуйте с ней.

Еще можно посмотреть [issues/39](https://github.com/yandex-money/yandex-checkout-payments-swift/issues/39) и обновленную инструкцию по [TrustDefender](https://github.com/yandex-money/yandex-checkout-payments-swift#trustdefender)

**Comment by oltv00** [comment]
@yargeel 
А можете показать реализацию методов ?

```
  func tokenizationModule(_ module: TokenizationModuleInput,
                          didTokenize token: Tokens,
                          paymentMethodType: PaymentMethodType)
```

и

```
  func didFinish(on module: TokenizationModuleInput,
                 with error: YandexCheckoutPaymentsError?)
```

**Comment by yargeel** [comment]
Добрый вечер

func tokenizationModule(_ module: TokenizationModuleInput,
                            didTokenize token: Tokens,
                            paymentMethodType: PaymentMethodType) {
        DispatchQueue.main.async { [weak self] in
        guard let strongSelf = self else { return }
            strongSelf.token = token
            strongSelf.paymentMethodType = paymentMethodType
            
            APESuperHUD.show(style: .loadingIndicator(type: .standard), title: nil, message: "Отправляем...")
            
            let jsonRequest = ...
            
            Alamofire.request("\(App.BASEURL)/linkcard", method: .post, parameters: [:], encoding: jsonRequest, headers: hdrs())
                .responseJSON {
                    response in
                    
                    APESuperHUD.dismissAll(animated: true)
                    App.this.paymentToken = strongSelf.token?.paymentToken ?? ""
                    
                    if let data = response.result.value {
                        reportEvent("Карта привязана", [:])
                        
                        let jsonResponse = JSON(data)
                        strongSelf.url3ds = jsonResponse["url"].stringValue
                        module.start3dsProcess(requestUrl: strongSelf.url3ds)
                    }
            }
        }
    }

    func didFinish(on module: TokenizationModuleInput) {
        DispatchQueue.main.async { [weak self] in
            guard let strongSelf = self else { return }
            strongSelf.dismiss(animated: true)
        }
    }

**Comment by oltv00** [comment]
@yargeel 
А можете отследить из какого кода он попадает в поток где падает.
По логу кажется что проблема где то в `APESuperHUD.show(style...`

**Comment by yargeel** [comment]
Да, проверили и поправили, спасибо.
Новая проблема :( точнее, проблемы: 
1) AppStore Connect Operation Error: Error ITMS-90087: "Unsupported Architectures. The executable for hoba.app/Frameworks/TrustDefender.framework contains unsupported architectures [x86_64, is86]
2) Error ITMS-90209: Invalid segment alignment. The app binary at hoba.app/Frameworks/TrustDefender.framework/TrustDefender does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.
3) Error ITMS-90125: The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid. ...
4) Warning ITMS-90080: The executable Payload/hoba.app/Frameworks/TrustDefender.framework is not a position independent executable. ...

Подскажите, пожалуйста, что с этим делать?

**Comment by oltv00** [comment]
@yargeel 
Кажется что нужно выполнить пункт 3 из [README.md](https://github.com/yandex-money/yandex-checkout-payments-swift#trustdefender)

> Добавьте в Build Phases -> New Run Script Phase, и добавьте скрипт из файла strip_framework.sh

**Comment by yargeel** [comment]
Сработало, спасибо!
