### ISSUE TITLE
Не работает русская локализация

### ISSUE THREAD

**Issue by whalemare** [yandex-money/yandex-checkout-payments-swift#41]
1. Создаю новый проект и подключаю туда `yandex-checkout-payments-swift`
2. Убираю английский язык и устанавливаю русский в настройках проекта
<img width="934" alt="Снимок экрана 2019-10-17 в 15 43 21" src="https://user-images.githubusercontent.com/9128731/66993092-34807b80-f0f5-11e9-813a-b2e8900c2756.png">
3. Захожу в настройку сборки и указываю явное использование русского языка
<img width="907" alt="Снимок экрана 2019-10-17 в 15 43 35" src="https://user-images.githubusercontent.com/9128731/66993199-5974ee80-f0f5-11e9-977c-ab356d7096d7.png">
4. Запускаю приложение и при показе формы оплаты, вижу английский текст, в то время как вся остальная часть приложения локализована

![Снимок экрана 2019-10-17 в 15 50 41](https://user-images.githubusercontent.com/9128731/66993518-e61fac80-f0f5-11e9-8861-4731ec6779cb.png)

Что я делаю не так, чтобы локализовать библиотеку?

**Comment by crazystik** [comment]
Тоже сталкивался с этим, но для меня решением послужила переустановка самого приложения на русский язык.
![Снимок экрана](https://user-images.githubusercontent.com/15373840/71502905-580a3400-28a5-11ea-943a-e4ba4d30738b.png)

**Comment by oltv00** [comment]
@whalemare 
Привет!
Актуальна ли еще проблема?

**Comment by whalemare** [comment]
Привет, около недели назад мне написали в личку с такой проблемой (т.к. мы юзаем вашу библиотеку [через бридж](https://github.com/lamantin-group/react-native-yandex-payment))и спросили решения, я перенаправил сюда.
В настоящий момент нет возможности проверить, думаю можно закрыть Issue, а я переоткрою в случае чего.

**Comment by oltv00** [comment]
@whalemare 

Ок!
