### ISSUE TITLE
Если выставить на iOS 13 темную тему, то не видно текста на белом фоне

### ISSUE THREAD

**Issue by qwerkly** [yandex-money/yandex-checkout-payments-swift#42]
![photo_2019-10-05_11-55-32](https://user-images.githubusercontent.com/11718301/67567465-9f076c00-f732-11e9-814e-cf1304552187.jpg)

**Comment by oltv00** [comment]
@qwerkly 
https://github.com/yandex-money/yandex-checkout-payments-swift/releases/tag/2.3.0
