### ISSUE TITLE
Размер приложения

### ISSUE THREAD

**Issue by pavlentus32** [yandex-money/yandex-checkout-payments-swift#43]
Здравствуйте! 

Такая ситуация: у нас приложение написано на Objective-C, на устройстве занимает 5 мегабайт. Интегрировали ваш SDK, приложение стало занимать 41 мегабайт. 

Есть какие-то варианты уменьшения размера? Кроме тех, которые указаны тут [https://developer.apple.com/library/archive/qa/qa1795/_index.html](url)

**Comment by oltv00** [comment]
@pavlentus32 
Скорее всего оптимизировать вес не получится.
Для этого необходим глобальные рефакторинг, и не факт что он сильно поможет.
