### ISSUE TITLE
Повторная оплата

### ISSUE THREAD

**Issue by robotsage** [yandex-money/yandex-checkout-payments-swift#44]
Добрый день!
У класса BankCardRepeatPresenter пустые реализации методов start3dsProcess. Какой процесс должен быть для повторной оплаты c 3ds и без в приложении, если бэкенд проекта интегированный с Яндекс Кассой, возвращает мне paymentMethodID?

**Comment by oltv00** [comment]
@robotsage 
>У класса BankCardRepeatPresenter пустые реализации методов start3dsProcess.

Это ошибка на нашей стороне.
В течении дня подготовим версию с исправлением.

>Какой процесс должен быть для повторной оплаты c 3ds и без в приложении, если бэкенд проекта интегированный с Яндекс Кассой, возвращает мне paymentMethodID?

Нужно использовать `TokenizationFlow = .bankCardRepeat`

**Comment by oltv00** [comment]
@robotsage 
https://github.com/yandex-money/yandex-checkout-payments-swift/releases/tag/2.3.1

**Comment by robotsage** [comment]
@oltv00 спасибо!
