### ISSUE TITLE
Получаю "no available payment methods"

### ISSUE THREAD

**Issue by narmiel** [yandex-money/yandex-checkout-payments-swift#47]
На и тестовом ключе, и на live_ та же самая проблема, нет доступных методов оплаты. Пробовал не задавать tokenizationSettings вообще, пробовал руками в 
tokenizationSettings: TokenizationSettings(paymentMethodTypes: paymentMethodTypes)
ставить 1-2 метода, не помогает.

Только с параметром testModeSettings есть методы оплаты. Что может быть?

**Comment by oltv00** [comment]
@narmiel 
Передайте параметр `isLoggingEnabled`, посмотрите в консоле ответ на запрос `payment_options`.

Если там данных нет, нужно обратиться к менеджеру по подключению, там исправят.
Если там есть данные, будем разбираться, значит проблема где то при интеграции самой библиотеки в iOS проект, или в библиотеке.

**Comment by narmiel** [comment]
Спасибо, isLoggingEnabled помог, увидел в консоли что amount 0 отправлялся.
