### ISSUE TITLE
Попытка сборки на реальное устройство 

### ISSUE THREAD

**Issue by Tawfikk** [yandex-money/yandex-checkout-payments-swift#48]
При попытке собрать проект на реальное устройство, получаю ошибку: 

`YandexCheckoutPayments/YandexCheckoutPayments.framework/YandexCheckoutPayments' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.`

`YandexCheckoutPayments/YandexCheckoutPayments.framework/YandexCheckoutPayments' for architecture arm64
`

Здесь проблема в самой либе, как мне кажется. Как можно ее устранить ? 
Пытался запускать на устройстве **`5S, 12.4`**

**Comment by oltv00** [comment]
Привет!
На текущий момент необходимо выключать bitcode.

https://github.com/yandex-money/yandex-checkout-payments-swift/blob/master/README.md#trustdefender

```
Если во время сборки проекта вы видите сообщение с ошибкой о TrustDefender.framework/TrustDefender' does not contain bitcode, необходимо выключить bitcode у основного таргета проекта
```

**Comment by Tawfikk** [comment]
Помогло, спасибо
