### ISSUE TITLE
Не подключается Trust Defender

### ISSUE THREAD

**Issue by Xoul28** [yandex-money/yandex-checkout-payments-swift#52]
Были выполнены все шаги из инструкции https://checkout.yandex.com/developers/payment-forms/ios-sdk
А также из обсуждения https://github.com/yandex-money/yandex-checkout-payments-swift/issues/31
Проект при билде падает с 33+ ошибками внутри фреймворка 
<img width="1440" alt="Снимок экрана 2020-02-07 в 1 02 48" src="https://user-images.githubusercontent.com/4996538/73982600-98011400-4945-11ea-9b04-3feb58a16213.png">

Внутрь проекта фреймворк не добавлен как и говорилось в обсуждении, папку как оставлял виртуальной, так и менял ей path на одноименную в корне проекта.
<img width="1440" alt="Снимок экрана 2020-02-07 в 1 04 05" src="https://user-images.githubusercontent.com/4996538/73982677-c41c9500-4945-11ea-980c-5691fa01ebb1.png">

Писал в техподдержку там предложили подключить slice скрипт, что и было сделано
![photo_2020-02-03_16-25-18](https://user-images.githubusercontent.com/4996538/73982776-fded9b80-4945-11ea-9335-187e8d12e68a.jpg)

Сам фреймворк имеет внутри нормальную структуру и виден внутри проекта, без проблем импортируется 
<img width="1440" alt="Снимок экрана 2020-02-07 в 1 10 03" src="https://user-images.githubusercontent.com/4996538/73983051-97b54880-4946-11ea-8033-6400bb3c0779.png">

Также в framework search paths был добавлен - $(PROJECT_DIR)/Frameworks 
что абсолютно не решило проблему
<img width="1440" alt="Снимок экрана 2020-02-07 в 1 11 15" src="https://user-images.githubusercontent.com/4996538/73983127-c0d5d900-4946-11ea-8e45-796571f2a1b5.png">

На просьбу прислать более детальную инструкцию или помочь с образовавшейся проблемой поддержка ответила отказом сказав что инструкция итак достаточно детальная.

**Comment by oltv00** [comment]
@Xoul28 
Есть возможность прислать тестовый проект с интегрированным SDK?
Я пройду по шагам и попытаюсь выяснить на каком этапе возникла ошибка.

**Comment by Xoul28** [comment]
[YandexTests2.zip](https://github.com/yandex-money/yandex-checkout-payments-swift/files/4169741/YandexTests2.zip)

Вот собственно, вчера еще возился с ним поэтому финальное состояние может отличаться от того что на скриншотах
Буду благодарен если укажете на ошибку

**Comment by chepil** [comment]
Проблема в этом:

Добавьте 
YandexTests2/Bridging_Header.h

Содержимое файла 
`#import <CommonCrypto/CommonCrypto.h>`

Скриншоты - 

<img width="974" alt="Снимок экрана 2020-02-07 в 11 57 24" src="https://user-images.githubusercontent.com/1425370/74015184-340c3900-49a1-11ea-8760-80bee0e12873.png">

<img width="924" alt="Снимок экрана 2020-02-07 в 11 59 06" src="https://user-images.githubusercontent.com/1425370/74015225-44241880-49a1-11ea-8eb0-2c7030b32d77.png">

После этого, у меня Ваш проект собрался.

**Comment by chepil** [comment]
Удалил Pods, пересобрал проект, опять не работает... мистика, сейчас разберусь...

**Comment by Xoul28** [comment]
К сожалению это не решило проблему
<img width="1440" alt="Снимок экрана 2020-02-07 в 12 09 47" src="https://user-images.githubusercontent.com/4996538/74015994-bf39fe80-49a2-11ea-8985-8fe59dbdb8b0.png">
<img width="1440" alt="Снимок экрана 2020-02-07 в 12 10 11" src="https://user-images.githubusercontent.com/4996538/74016029-cd881a80-49a2-11ea-94c9-ba04fb78d38d.png">
<img width="609" alt="Снимок экрана 2020-02-07 в 12 10 54" src="https://user-images.githubusercontent.com/4996538/74016093-e7c1f880-49a2-11ea-8790-8c45c29afdc1.png">

**Comment by chepil** [comment]
Фреймворк кривой. С моим работает, я свой проекту подсовывал, вот и работало. crypto похоже не при чем, извиняюсь 
[framework.zip](https://github.com/yandex-money/yandex-checkout-payments-swift/files/4169925/framework.zip)

**Comment by Xoul28** [comment]
<img width="1440" alt="Снимок экрана 2020-02-07 в 12 37 49" src="https://user-images.githubusercontent.com/4996538/74018329-c400b180-49a6-11ea-8395-839b49e2bd19.png">
Закинул ваш, тоже не помогло
На всякий сделал pod deintegrate и заново сгенерил воркспейс, та же ошибка 
А то что структура у фреймворка сильно странная это норма? В обсуждениях в одной из первых ссылок его раскорячивали и убирали симлинки насколько я понял. Вы его просто в папку закидывали?

**Comment by chepil** [comment]
У меня вот так собирается, запускается, ошибок вообще при сборке нет

[YandexTests2.zip](https://github.com/yandex-money/yandex-checkout-payments-swift/files/4170026/YandexTests2.zip)

**Comment by Xoul28** [comment]
<img width="1440" alt="Снимок экрана 2020-02-07 в 12 54 00" src="https://user-images.githubusercontent.com/4996538/74019572-ec89ab00-49a8-11ea-8289-4364e6426775.png">
Те же проблемы...
У вас фреймворк добавлен в проект, а в обсуждениях что приводил по ссылке говорилось что не надо так делать 
Где правда?) 
Совершенно не представляю пока куда копать дальше

**Comment by oltv00** [comment]
@Xoul28 
Довольно странно.
Я скачал архив по первой ссылке, и просто запустил.
Все сбилдилось без ошибок.

А какая версия Xcode используется?

**Comment by oltv00** [comment]
@Xoul28 
>Те же проблемы... У вас фреймворк добавлен в проект, а в обсуждениях что приводил по ссылке говорилось что не надо так делать Где правда?) Совершенно не представляю пока куда копать дальше

TrustDefender.framework необходимо добавлять в проект, если используется новая версия фреймворка - `ThreatMetrix iOS SDK 5.4-84`, т.к. при запуске проекта будет ошибка `dyld: Library not loaded: @rpath/TrustDefender.framework/TrustDefender`

**Comment by Xoul28** [comment]
Версия xcode 10.3
Действительно странно, проект что скинули по архиву выше у меня также не завелся

**Comment by oltv00** [comment]
@Xoul28 
>Версия xcode 10.3

Последняя версия SDK поддерживается только на Xcode 11
Можно использовать версию `2.2.2` на Xcode 10.

Проект который первый по ссылке успешно собрался на Xcode 10, и SDK `2.2.2`

Но лучше конечно перевести проект, в который происходит интеграция, на последний Xcode, и интегрировать последнюю версию SDK.

**Comment by Xoul28** [comment]
Спасибо, последний комментарий помог
Версия 2.2.2 на 10 xcode собралась без проблем
На 11 потесчу чуть позднее, ишку закрываю
