### ISSUE TITLE
Кастомизация 

### ISSUE THREAD

**Issue by Tawfikk** [yandex-money/yandex-checkout-payments-swift#54]
Можно ли использовать сторонний дизайн, к примеру, для ввода суммы денег и так же ввода данных карты ?

**Comment by oltv00** [comment]
@Tawfikk 

Библиотека на вход принимает какое то значение и валюту, т.е. ввод суммы денег происходит вне UI библиотеки.

Для ввода данных карты используется экран, который находится внутри библиотеки.
Есть 2 варианта:
1. Использовать текущий экран, с возможностью [кастомизации цвета](https://github.com/yandex-money/yandex-checkout-payments-swift#Кастомизация-интерфейса).

2. Сделать `fork`, и изменить экран как угодно.

**Comment by Tawfikk** [comment]
Благодарю за ответ!
