### ISSUE TITLE
Использование нескольких касс

### ISSUE THREAD

**Issue by Tawfikk** [yandex-money/yandex-checkout-payments-swift#56]
Хотелось бы узнать, можно ли провести платеж ApplePay на разные яндекс кассы с одного устройства ? 

К примеру, есть список проектов для пожертвования, и эти проекты с разных фондов, где у каждого фонда свой ключ для яндекс кассы, пользователь тапаем и хочет сделать пожертвования через ApplePay, на данный момент выдает ошибку и хотим с этим разобраться.

**Comment by Tawfikk** [comment]
@oltv00

**Comment by oltv00** [comment]
@Tawfikk Привет!
Да, можно.
Достаточно передавать разные `clientApplicationKey` для каждого "фонда".

Если возникает ошибка, то необходимо поддержать возможность оплаты через Apple Pay для конкретного `clientApplicationKey`

**Comment by Tawfikk** [comment]
Спасибо за ответ!

**Comment by Tawfikk** [comment]
Хочу уточнить, для каждой кассы надо обмениваться с сертификатами для настройки ApplePay с одного аккаунта разработчика ?

**Comment by oltv00** [comment]
> Хочу уточнить, для каждой кассы надо обмениваться с сертификатами для настройки ApplePay с одного аккаунта разработчика ?

Я узнаю и вернусь с ответом.

**Comment by oltv00** [comment]
@Tawfikk 
Да, так можно.
Можно прогрузить один сертификат, для нескольких shopId, и просто использовать разные `clientApplicationKey`
