### ISSUE TITLE
strip_framework.sh

### ISSUE THREAD

**Issue by tonybragin** [yandex-money/yandex-checkout-payments-swift#60]
3. Добавьте в Build Phases -> New Run Script Phase, и добавьте скрипт из файла strip_framework.sh

Подскажите, где найти этот strip_framework.sh

**Comment by oltv00** [comment]
@tonybragin 
Привет.

Он должен быть в архиве, который может предоставить менеджер по подключению SDK.
ThreatMetrix iOS SDK 6.0-91 With Bitcode.zip
![Screenshot 2020-04-30 at 14 02 30](https://user-images.githubusercontent.com/14943414/80703378-536fb980-8aeb-11ea-9c9b-d4cf0fb5c286.png)
