### ISSUE TITLE
Кастомизация ссылки на лицензионное соглашение

### ISSUE THREAD

**Issue by maxkazakov** [yandex-money/yandex-checkout-payments-swift#61]
Возможно ли поддержать переопределение ссылки на соглашение? Сейчас в коде используется приватная константа
![image](https://user-images.githubusercontent.com/17107905/81385993-b84f9300-912d-11ea-9bbc-b8ee914a2dc4.png)

**Comment by oltv00** [comment]
@maxkazakov 
Привет!
К сожалению такой возможности нет, и скорее всего не будет.
