### ISSUE TITLE
Ошибка - Компиляция с учетом iOS 14 SDK

### ISSUE THREAD

**Issue by hellc** [yandex-money/yandex-checkout-payments-swift#65]
Style.swift и enum Style проекта пересекается со Style из iOS 14 SDK.

<img width="1252" alt="Screenshot 2020-07-01 at 10 33 01" src="https://user-images.githubusercontent.com/750178/86223053-b931fd80-bb8f-11ea-8e3c-c4853378dee6.png">

Рекомендую переименовать по аналогии с: https://github.com/hellc/yandex-checkout-payments-swift/commits?author=hellc
Переименование решает проблему. PR делать не буду.

**Comment by hellc** [comment]
Если кому-то не терпится ждать апдейта то вот:

`pod 'YandexCheckoutPayments', :git => 'https://github.com/hellc/yandex-checkout-payments-swift.git', :branch => 'master'`

**Comment by oltv00** [comment]
@hellc 
Спасибо, взяли в работу.

**Comment by Tawfikk** [comment]
@oltv00 этот update уже слит в либу ?

**Comment by oltv00** [comment]
@Tawfikk 
да
