### ISSUE TITLE
TrustDefender

### ISSUE THREAD

**Issue by shadealix** [yandex-money/yandex-checkout-payments-swift#8]
Здравствуйте, вот [тут,](https://kassa.yandex.ru/docs/client-sdks/#sdk-dlq-ios) в инструкции интеграции сдк написано, что необходимо установить через cocoapods и добавить TrustDefender.framework

где, собственно можно взять данный фреймворк? на гитхабе я нашел, но его яндекс не хочет признавать. 

в выкачаном ExampleProject после установки подов та же проблема - отсутствие этого фреймворка.

**Comment by NullIsOne** [comment]
Присоединяюсь к вопросу.
С версией TrustDefender.framework из других проектов, sdk не компилится. 
Где взять подходящую версию непонятно.

**Comment by NullIsOne** [comment]
Нашёл в соседнем закрытом issue

> #!/bin/bash
git clone https://bitbucket.org/haymob/trustdefender.git
mkdir -pv Carthage/Build/iOS
mv trustdefender/TrustDefender.framework Carthage/Build/iOS
rm -rf trustdefender
carthage update --platform iOS

К битбакету ещё доступ надо запросить.

Ребята из Яндекса, поправьте инструкцию, что ли..

**Comment by MetalheadSanya** [comment]
Эту библиотеку вам выдадут сотрудники Яндекс.Касса при заключении договора на оказание услуг платежа через мобильное SDK

**Comment by NullIsOne** [comment]
Спасибо.
Библиотеку нам выдали.
Но всё же инструкцию на сайте следует поправить, чтобы было ясно, что библиотека будет доступна только после заключения договора.

**Comment by balkarov** [comment]
Так же проблема. А как её установить? Добавил в проект, добавил в Link Binary With Libraries. Но все равно YandexCheckoutPayments ругается ,что no such module TrustDefender

**Comment by oltv00** [comment]
Актуальная инструкция в [README.md](
https://github.com/yandex-money/yandex-checkout-payments-swift/blob/master/README.md)
На сайте инструкция обновится в ближайшее время.
